### ISSUE TITLE
photos from non-inat sources

### ISSUE THREAD

**Issue by wcornwell** [tmesaglio/Australian-plant-photos#12]
We should check what ALA has pulled in as a first step?

**Comment by tmesaglio** [comment]
List of sources we should look at:
[Flickr](https://www.flickr.com)
[Australian Plant Image Index](https://www.anbg.gov.au/photo/genus-photo-search.html)

[PlantNET](https://plantnet.rbgsyd.nsw.gov.au)
[Florabase](https://florabase.dpaw.wa.gov.au)
[FloraNT](http://eflora.nt.gov.au)
[VICFLORA](https://vicflora.rbg.vic.gov.au)
[Key to Tasmanian Vascular Plants](https://www.utas.edu.au/dicotkey/)
[Electronic Flora of South Australia](http://www.flora.sa.gov.au)

[Australian Tropical Rainforest Plants](https://apps.lucidcentral.org/rainforest/text/intro/index.html)
[WATTLE: Acacias of Australia](https://apps.lucidcentral.org/wattle/text/intro/index.html)
[EUCLID Eucalypts of Australia](https://apps.lucidcentral.org/euclid/text/intro/index.html)

**Comment by wcornwell** [comment]
all done?  

BTW you can make this in Github

- [ ] thing to do 
- [ ] other thing to do 

and it's satisfying to tick them off

**Comment by tmesaglio** [comment]
so close!!

Just two sources left:

1. Have to do another pass at the Australian Plant Image Index, as I accidentally found out that not all images in there have been absorbed by the ALA. So need to get those leftover ones that are only on the APII and nowhere else.

2. Flickr, which I need to ask David about re best way to search. Looking at their API, seems like it's not really designed for searching for a big list of names

**Comment by tmesaglio** [comment]
Other than those 2, are there any others you can think of that I've missed?

**Comment by wcornwell** [comment]
maybe check http://legacy.tropicos.org/ImageSearch.aspx , which is mostly neotropical but might have some wet tropics stuff

 @eflowerproject ?  any other places?

**Comment by wcornwell** [comment]
An aside but the flora here in Portugal has gone into 100% into images.  check out: https://flora-on.pt/#1Arenaria+montana

or if you're wondering what Arenaria you have: https://flora-on.pt/#/1arenaria

**Comment by tmesaglio** [comment]
There’s supposed to be a Hakea lucid key page, as well as a Solanum one, but neither work when I follow the links
