### ISSUE TITLE
entities to delete from APC file

### ISSUE THREAD

**Issue by tmesaglio** [tmesaglio/Australian-plant-photos#2]
Things that we're deleting:

- provisional names/species
- hybrids
- any row that does not contain at least one 'native' cell

**Comment by wcornwell** [comment]
This probably could be done in a `match_inat_and_apc.R` script?

**Comment by tmesaglio** [comment]
to remove the phrase names, I should be able to search for the word 'sp.' in each cell right?

**Comment by wcornwell** [comment]
They're both identified in a column in apni file, but have to check the APC file...

**Comment by tmesaglio** [comment]
ah yep, the column is 'nameType'
