### ISSUE TITLE
Tasmania test case

### ISSUE THREAD

**Issue by tmesaglio** [tmesaglio/Australian-plant-photos#4]
Just uploaded the Tasmania data; note that this also includes observations from Macquarie Island, which belongs to Tasmania

EDIT: redownloaded this file to exclude the Macquarie Island observations

**Comment by wcornwell** [comment]
If you do 

```
library(tidyverse)
apc<-read_csv("data/states_islands_species_list.csv")
tas<-filter(apc,Tas=="native")
```

that should give you the APC list for Tas Natives to compare to

**Comment by tmesaglio** [comment]
some very preliminary stats.

Master APC list for Tasmania = 1740 accepted native species
iNaturalist list (pre-cleaning) = 1515 species

giving us 87.1% of all Tasmanian species uploaded to iNat!

**Comment by wcornwell** [comment]
where is your 1515 coming from?  I'm getting 1396 from iNat?

**Comment by wcornwell** [comment]
ah i see, 1515 is you use the whole string, 1396 from binomials...

**Comment by tmesaglio** [comment]
Ah so did I use the wrong column? I did it for column AK, 'scientific_name'

**Comment by wcornwell** [comment]
<img width="684" alt="Screen Shot 2022-02-28 at 11 02 12 am" src="https://user-images.githubusercontent.com/5534161/155905753-ea5daf70-61dc-4920-8f8d-cc5b0778a7c0.png">

**Comment by wcornwell** [comment]
no i was using the same, just trimming to the first two words

**Comment by tmesaglio** [comment]
got you, so I inadvertently included 120 duplicates due to subspecies

**Comment by tmesaglio** [comment]
so 80.2% pre-cleaning

**Comment by wcornwell** [comment]
a lot of species have been photographed in Vic, maybe we should start with just Tassy endemics?

**Comment by tmesaglio** [comment]
yeah sounds good to me

**Comment by wcornwell** [comment]
i'm getting 463 endemics, does that sounds right?

**Comment by tmesaglio** [comment]
yeah seems pretty reasonable to me

**Comment by wcornwell** [comment]
here is an example of synonym issues: https://www.inaturalist.org/taxa/950630-Knowltonia-crassifolia

**Comment by wcornwell** [comment]
example of one not in iNat but it is here: https://biocache.ala.org.au/occurrences/d2d17577-002f-441b-a31e-438ad608a89c

**Comment by tmesaglio** [comment]
what's the issue for the Knowltonia? From memory that one should map to Anemone in APC

**Comment by wcornwell** [comment]
> what's the issue for the Knowltonia? From memory that one should map to Anemone in APC

yup, just have to figure out how to do the mapping in code

**Comment by wcornwell** [comment]
|family           | endemic_species| photographed_in_inat|
|:----------------|---------------:|--------------------:|
|Apiaceae         |               8|                    6|
|Araliaceae       |               1|                    0|
|Asparagaceae     |               1|                    0|
|Asphodelaceae    |               2|                    2|
|Asteliaceae      |               5|                    3|
|Asteraceae       |              60|                   44|
|Blandfordiaceae  |               1|                    1|
|Brassicaceae     |               3|                    0|
|Campanulaceae    |               1|                    1|
|Campynemataceae  |               1|                    1|
|Caryophyllaceae  |               1|                    0|
|Casuarinaceae    |               4|                    4|
|Crassulaceae     |               1|                    0|
|Cunoniaceae      |               3|                    3|
|Cupressaceae     |               3|                    3|
|Cyperaceae       |              21|                    7|
|Dilleniaceae     |               1|                    1|
|Droseraceae      |               1|                    1|
|Elaeocarpaceae   |               2|                    2|
|Ericaceae        |              58|                   46|
|Escalloniaceae   |               1|                    1|
|Euphorbiaceae    |               1|                    0|
|Fabaceae         |               8|                    4|
|Gentianaceae     |               6|                    3|
|Gleicheniaceae   |               2|                    1|
|Gunneraceae      |               1|                    1|
|Haemodoraceae    |               1|                    1|
|Haloragaceae     |               1|                    1|
|Hydatellaceae    |               1|                    0|
|Hymenophyllaceae |               1|                    1|
|Hypericaceae     |               1|                    0|
|Iridaceae        |               2|                    2|
|Isoëtaceae       |               3|                    1|
|Juncaceae        |               4|                    1|
|Lamiaceae        |               3|                    3|
|Lauraceae        |               1|                    1|
|Linaceae         |               1|                    0|
|Loganiaceae      |               1|                    1|
|Lycopodiaceae    |               1|                    0|
|Malvaceae        |               2|                    1|
|Menyanthaceae    |               2|                    1|
|Myrtaceae        |              25|                   23|
|Nothofagaceae    |               1|                    1|
|Onagraceae       |               5|                    1|
|Orchidaceae      |              66|                   49|
|Orobanchaceae    |               6|                    2|
|Phyllanthaceae   |               1|                    1|
|Picrodendraceae  |               1|                    1|
|Pittosporaceae   |               4|                    3|
|Plantaginaceae   |              12|                    9|
|Poaceae          |              21|                    7|
|Podocarpaceae    |               4|                    4|
|Proteaceae       |              17|                   15|
|Ranunculaceae    |              13|                    7|
|Restionaceae     |               9|                    3|
|Rhamnaceae       |               7|                    5|
|Rhizophoraceae   |               9|                    9|
|Rosaceae         |               4|                    4|
|Rubiaceae        |               1|                    0|
|Rutaceae         |              11|                    7|
|Santalaceae      |               2|                    2|
|Sapindaceae      |               1|                    1|
|Solanaceae       |               1|                    0|
|Stylidiaceae     |               3|                    3|
|Tetracarpaeaceae |               1|                    1|
|Thymelaeaceae    |               7|                    7|
|Violaceae        |               1|                    1|
|Xyridaceae       |               3|                    2|

**Comment by tmesaglio** [comment]
cool. Some of these numbers will change a bit after synonym matching, etc. 
eg, there are at least 2 Tassie species that are in iNat but not in APC for some reason (despite them being described in 2013)

**Comment by tmesaglio** [comment]
this is one of the weird ones: https://www.inaturalist.org/observations?taxon_id=898863

it actually is in APC (https://biodiversity.org.au/nsl/services/rest/name/apni/245358/api/apniFormat), but not accepted yet. The name isn't in the master APC file/export though

**Comment by wcornwell** [comment]
![image](https://user-images.githubusercontent.com/5534161/155916724-82f168f7-2d15-41c9-ae01-f844f160f658.png)

**Comment by tmesaglio** [comment]
the oldest described one is unphotographed!! Which species is it?

**Comment by wcornwell** [comment]
Epilobium obscurum

**Comment by tmesaglio** [comment]
that's another APC error. There are 3 Tassie obs, but it's a non-native (European species)

**Comment by wcornwell** [comment]
next is Crassula moschata but that's not really an endemic

**Comment by tmesaglio** [comment]
also on sub-Antarctic islands?

**Comment by wcornwell** [comment]
and Veronica novae-hollandiae

**Comment by wcornwell** [comment]
Epacris mucronulata might be an good compelling example for the paper--hasn't been collected since 2006, no known pics?  at least that I can find

**Comment by tmesaglio** [comment]
Veronica novae-hollandiae is on iNat (with two TAS obs) as Veronica novaehollandiae

**Comment by wcornwell** [comment]
> Veronica novae-hollandiae is on iNat (with two TAS obs) as Veronica novaehollandiae

hyphens in species names are a nightmare. adding to todo list in script

**Comment by tmesaglio** [comment]
the Veronica is not an APC error, so I'll fix that now on my end

**Comment by tmesaglio** [comment]
putative photo of the Epacris dated 2019: https://www.utas.edu.au/dicotkey/dicotkey/EPACRIDS/ZEpacris_mucronulata.htm
unsure if it's correct

**Comment by wcornwell** [comment]
interesting, someone should get greg jordan to post on iNat.  Hierochloe fraseri is another one

**Comment by tmesaglio** [comment]
check out the comprehensive page for Hierochloe
https://www.utas.edu.au/docs/plant_science/field_botany/species/monocots/poaceasp/hierfras.html
