### ISSUE TITLE
errors in APC

### ISSUE THREAD

**Issue by wcornwell** [tmesaglio/Australian-plant-photos#5]
collecting APC errors

**Comment by wcornwell** [comment]
Gastrodia sesamoides should be listed as native to Tasmania

**Comment by wcornwell** [comment]
Chordifex monocephalus should be native to Tasmania and not WA

**Comment by tmesaglio** [comment]
Cyperus stoloniferus (iNat) is given as Cyperus stolonifer in APC, but the former is not listed as an orthographic variant

Cenchrus alopecuroides (iNat) is given as Cenchrus purpurascens in APC, without the former recognised as a synonym

Trema orientale (iNat) is given as Trema orientalis in APC but the former is not listed as an orthographic variant

Hygrophila ringens (iNat) is given as Hygrophila angustifolia in APC, without the former recognised as a synonym

Euphrasia amplidens was described in 2013 and has iNat observations (Tasmania), and the name is present as unaccepted in APC, but it was not in the APC export

Viola curtisiae has iNat observations (Tasmania, Victoria), but is treated by APC as a synonym of Viola hederacea subsp. Baw Baws Vic. Herbarium (so we need to resurrect this phrase name possibly).

**Comment by wcornwell** [comment]
Calochilus robertsonii should be listed as native in Tasmania

**Comment by tmesaglio** [comment]
Following species should all be changed to non-native to Australia:

Bidens subalternans - APC says native to WA and NT, yet all other sources (including Florabase and NTFlora) say non-native to Australia. 

Senna sophera - APC says native to QLD, yet all other sources say non-native to Australia.

Isolepis levynsiana - APC says native to TAS, yet all other sources say non-native to Australia (Africa only). 

Myosotis discolor - APC says native to SA, yet all other sources say non-native to Australia. 

Spermacoce remota - APC says native to QLD, yet all other sources say non-native to Australia. 

Spermacoce exilis - APC says native to Xmas Island, yet all other sources say non-native to Australia. 

Andrographis paniculata - APC says native and naturalised to Xmas Island, yet all other sources say non-native to Australia. Native part needs to be removed (also how could something possibly be both native and naturalised to Xmas Island given its size?)

Veronica serpyllifolia - APC says native to VIC, but most online sources say it's spuriously native; leave as is?

Malvastrum coromandelianum - APC (and PlantNET) says native to NSW, yet all other sources say non-native to Australia. 

Malvastrum americanum - APC says native to SA and native + naturalised to WA, yet all other sources say non-native to Australia. 

Sida spinoa - APC says native to NSW and WA, yet all other sources say non-native to Australia. 

Melochia pyramidata - APC says native to NSW, yet all other sources say non-native to Australia. 

Tribulus terrestris - APC says native to QLD, yet all other sources say non-native to Australia. 

Cardiospermum halicacabum - APC says native to WA, but it's actually a pre-European introduction, and so non-native.

**Comment by tmesaglio** [comment]
Following species should be changed to native for certain areas in Australia:

Pittosporum ferrugineum and Aidia racemosa should both be listed as native for Xmas Island, but they're currently listed as not present.

Ipomoea pes-caprae and Celtis paniculata should both be listed as native for Norfolk Island, but they're currently listed as not present.
