### ISSUE TITLE
weird error in R

### ISSUE THREAD

**Issue by tmesaglio** [tmesaglio/Australian-plant-photos#8]
when I try to run line 16 in 'synonym cleaning', it keeps giving me this error message:

Error in filter(step2_apc, nameType == "scientific") : 
  object 'nameType' not found

but nameType is clearly a valid column in that dataframe. I tested this with the other column names and have the same problem.

I copy pasted that line of code from one of the other R scripts where it works perfectly (and I'm using it in essentially the same context), so no clue what's going on here

**Comment by wcornwell** [comment]
push your most recent version and i'll see if i can replicate the error...

**Comment by tmesaglio** [comment]
just tried it again and it works....
no idea what happened
